name: county-prototype
version: 0.1.0

access: public

timeSpan:
  start: 2025-01-01T00:00:00Z
  end:   2044-12-31T23:00:00Z

# The base resolution of the data. This is used to determine the
# resolution of the data in the output files.
baseResolution: 1h
baseAggregation: mean

# The segmentation of the data.
segments:
  level1:
    description: "Primary segments"
    values:
      - buildings
      - industry
      - transport
geographies:
  level1:
    description: "Top-level geography"
    values:
      - 01
      - 03
      - 04
      - 05
      - 06
      - 07
      - 08
      - 09
      - 10
      - 12
      - 13
      - 14
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
  level2:
    description: "Optional sub-geography"
    values: []
      # if you don’t have any global second-level today, leave it empty
      # or list them under each top-level key later


# locations of the detailed configs:
apiConfig:        api/parameters.yaml
partitionConfig:  generator/partitioning.yaml
pipelineConfig:   generator/pipelines/county-prototype.yaml