/**
 * @fileoverview Local API server for Demand Toolkit
 *
 * This server provides OpenAPI 3.1 compliant endpoints for demand forecasting data.
 * It uses Express + OpenAPI Backend for routing/validation and DuckDB for querying Parquet files.
 *
 * **Architecture:**
 * - Static endpoints serve pre-generated JSON files (config, parameters, scenarios, globals)
 * - Dynamic /demand endpoint uses DuckDB to query nested Parquet structure
 * - CORS enabled for local development with Explorer frontend on port 5173
 *
 * **Data Structure:**
 * - Base scenarios: /api/data/base/{scenario_id}/data.parquet
 * - Parametric scenarios: /api/data/scenarios/{param1}={val1}/{param2}={val2}/.../data.parquet
 * - Aggregated tables: /api/data/aggregated/*.parquet (pre-computed for performance)
 *
 * **Performance:**
 * - Uses DuckDB in-memory database with persistent connection
 * - UNION queries combine base and scenario data with schema normalization
 * - Pre-aggregated tables provide 50-100x speedup for yearly queries
 *
 * @module local-server
 */

import express from 'express';
import cors from 'cors';
import { OpenAPIBackend } from 'openapi-backend';
import duckdb from 'duckdb';
import { fileURLToPath } from 'url';
import path from 'path';
import qs from 'qs';
import fs from 'fs';
import { parsePeriod, formatPeriod } from './utils.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const api = new OpenAPIBackend({ definition: './openapi.yaml' });

await api.init();

const app = express();

app.use(cors({
  origin: 'http://localhost:5173'
}));

app.use(express.json());

// route everything through OpenAPI‐Backend
app.use((req, res) =>
  api.handleRequest(
    {
      method: req.method,
      path: req.path,
      query: qs.parse(req.url.split('?')[1] || ''),
      body: req.body,
      headers: req.headers,
    },
    req,
    res
  )
);

/**
 * DuckDB database and connection (in-memory, persistent for session)
 * Used for querying Parquet files in /demand endpoint
 * @type {duckdb.Database}
 */
const db = new duckdb.Database(':memory:');

/**
 * Persistent DuckDB connection for Parquet queries
 * @type {duckdb.Connection}
 */
const conn = db.connect();

/**
 * Handler for geography endpoint - serves static files in JSON or GeoJSON format
 * @param {import('openapi-backend').Context} c - OpenAPI context
 * @param {import('express').Request} req - Express request
 * @param {import('express').Response} res - Express response
 */
api.register('getGeographies', (c, req, res) => {
  // Pick the format from ?format=… or default to json
  const fmt = (c.request.query.format === 'geojson' ? 'geojson' : 'json');
  const filename = `geographies.${fmt}`;
  const filepath = path.join(__dirname, 'data', filename);

  if (!fs.existsSync(filepath)) {
    return res.status(404).json({ error: 'Not found' });
  }

  // Set the right Content-Type
  if (fmt === 'geojson') res.type('application/geo+json');
  else              res.type('application/json');

  res.send(fs.readFileSync(filepath));
});

/**
 * Register static endpoint handlers for pre-generated JSON files
 *
 * These endpoints serve static JSON files generated by generate-api.js:
 * - /config → data/config.json (configuration metadata)
 * - /parameters → data/parameters.json (valid parameter values)
 * - /scenarios → data/scenarios.json (scenario combinations)
 * - /aggregations → data/aggregations.json (resolution-aggregation combinations)
 * - /globals → data/globals.json (pre-computed bounds and statistics)
 *
 * @example
 * GET /globals → { lower_bound: -20.41, upper_bound: 12497.73, bounds: {...} }
 */
const staticOps = [
  'getConfig',
  'getParameters',
  'getScenarios',
  'getAggregations',
  'getGlobals',
];
staticOps.forEach((op) => {
  api.register(op, (c, req, res) => {
    const base = op.replace(/^get/, '').toLowerCase();
    const filepath = path.join(__dirname, 'data', `${base}.json`);
    if (!fs.existsSync(filepath)) {
      return res.status(404).json({ error: 'Not found' });
    }
    res.type('application/json').send(fs.readFileSync(filepath));
  });
});


/**
 * Handler for /demand endpoint - returns time-series demand data with flexible aggregation
 *
 * This handler uses DuckDB to query Parquet files in a nested directory structure:
 * - /api/data/base/default/data.parquet (base scenario)
 * - /api/data/scenarios/param1=val1/param2=val2/.../data.parquet (parametric scenarios)
 *
 * Query optimization:
 * - Uses pre-aggregated tables for yearly queries when available (50-100x faster)
 * - Combines base and scenario files with UNION queries
 * - Applies predicate pushdown for efficient filtering
 *
 * @param {import('openapi-backend').Context} c - OpenAPI context with validated request
 * @param {import('express').Request} req - Express request
 * @param {import('express').Response} res - Express response
 *
 * @returns {Promise<void>} JSON array or CSV string of time-series data
 *
 * @example
 * // National yearly totals
 * GET /demand?period.start=2030&period.end=2031&period.resolution=1Y&period.aggregation=sum&geography=total&segment=total&scenarioId=default
 *
 * @example
 * // Geography breakdown
 * GET /demand?period.start=2030&period.end=2031&period.resolution=1Y&period.aggregation=sum&geography=all&segment=total&scenarioId=default
 */
api.register('getDemand', async (c, req, res) => {
  try {
    const { period, geography, segment, scenarioId } = c.request.query;
    const fmt = c.request.query.format || 'json';

    // 1) Pull out common filters
    const { start, end } = parsePeriod(c.request.query.period);
    const resolution   = period.resolution;   // '1h' | '1w' | '1M' | '1Y'
    const aggregation  = period.aggregation;  // 'mean' | 'sum'
    const geoFilter    = geography;
    const segFilter    = segment;
    const scenarioFilter = scenarioId;

    // 2) Map resolution → SQL truncation expression + alias
    let timeExpr, timeAlias;
    switch (resolution) {
      case '1h':
        timeExpr  = `combined_data.timestamp`;
        timeAlias = 'period';
        break;
      case '1d':
        timeExpr = `DATE_TRUNC('day', combined_data.timestamp)`;
        timeAlias = 'period';
        break;
      case '1w':
        timeExpr = `DATE_TRUNC('week', combined_data.timestamp)`;
        timeAlias = 'period';
        break;
      case '1M':
        timeExpr  = `DATE_TRUNC('month', combined_data.timestamp)`;
        timeAlias = 'period';
        break;
      case '1Y':
        timeExpr  = `DATE_TRUNC('year', combined_data.timestamp)`;
        timeAlias = 'period';
        break;
      default:
        throw new Error(`Unsupported resolution: ${resolution}`);
    }

    // 3) Choose aggregation function
    const aggFunc = aggregation === 'sum' ? 'SUM' : 'AVG';

    // 4) Build WHERE clauses
    const wheres = [
      `t.timestamp >= TIMESTAMP '${start}'`,
      `t.timestamp <=  TIMESTAMP '${end}'`
    ];

    // geography filter
    if (geoFilter !== 'all' && geoFilter !== 'total') {
      wheres.push(`t.geography = '${geoFilter}'`);
    }

    // segment filter
    if (segFilter !== 'all' && segFilter !== 'total') {
      wheres.push(`t.segment = '${segFilter}'`);
    }

    // scenario filter
    if (scenarioFilter !== undefined && scenarioFilter !== 'all') {
      wheres.push(`t.scenario_id = '${scenarioFilter}'`);
    }

    // 5) Decide GROUP BY keys and SELECT clause parts
    const groupBy = [ timeExpr ];
    const selectExtras = [];

    // geography
    if (geoFilter === 'total') {
      // national total
      selectExtras.push(`'total' AS geography`);
      // no GROUP BY
    }
    else if (geoFilter === 'all') {
      selectExtras.push(`combined_data.geography AS geography`);
      groupBy.push(`combined_data.geography`);
    }
    else {
      // single geography (already WHERE'd above)
      selectExtras.push(`'${geoFilter}' AS geography`);
    }

    // segment
    if (segFilter === 'total') {
      selectExtras.push(`'total' AS segment`);
    }
    else if (segFilter === 'all') {
      selectExtras.push(`combined_data.segment AS segment`);
      groupBy.push(`combined_data.segment`);
    }
    else {
      selectExtras.push(`'${segFilter}' AS segment`);
    }

    // scenario
    if (scenarioFilter === 'all') {
      selectExtras.push(`combined_data.scenario_id AS scenario_id`);
      groupBy.push(`combined_data.scenario_id`);
    }
    else {
      selectExtras.push(`'${scenarioFilter}' AS scenario_id`);
    }

    // 6) Build parquet path for demand query
    const dataDir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'data');

    const scenariosDir = path.join(dataDir, 'scenarios');
    const baseDir = path.join(dataDir, 'base');
    const aggregatedDir = path.join(dataDir, 'aggregated');

    let sql;

    console.log('🚀 Loading demand data...');

      // Try to use aggregated tables first for common queries
      const useAggregated = resolution === '1Y' && (geoFilter === 'all' || geoFilter === 'total' || segFilter === 'all' || segFilter === 'total');

      if (useAggregated && fs.existsSync(aggregatedDir)) {
        console.log('📊 Using pre-aggregated tables');

        // Choose appropriate aggregated table
        let aggregatedTable;
        if (geoFilter === 'all' && segFilter !== 'all' && segFilter !== 'total') {
          aggregatedTable = path.join(aggregatedDir, 'geography_yearly.parquet');
        } else if (segFilter === 'all' && geoFilter !== 'all' && geoFilter !== 'total') {
          aggregatedTable = path.join(aggregatedDir, 'segment_yearly.parquet');
        } else if (geoFilter === 'total' && segFilter === 'total') {
          aggregatedTable = path.join(aggregatedDir, 'national_yearly.parquet');
        }

        if (aggregatedTable && fs.existsSync(aggregatedTable)) {
          // Build aggregated query
          const wheres = [
            `CAST(year AS INTEGER) >= ${new Date(start).getFullYear()}`,
            `CAST(year AS INTEGER) <= ${new Date(end).getFullYear()}`
          ];

          // scenario filter for aggregated tables
          if (scenarioFilter !== undefined && scenarioFilter !== 'all') {
            wheres.push(`scenario_id = '${scenarioFilter}'`);
          }

          // geography filter for aggregated tables
          if (geoFilter !== 'all' && geoFilter !== 'total' && aggregatedTable.includes('geography')) {
            wheres.push(`geography = '${geoFilter}'`);
          }

          // segment filter for aggregated tables
          if (segFilter !== 'all' && segFilter !== 'total' && aggregatedTable.includes('segment')) {
            wheres.push(`segment = '${segFilter}'`);
          }

          const groupBy = ['year'];
          const selectExtras = [];

          // Add geography to output
          if (geoFilter === 'total') {
            selectExtras.push(`'total' AS geography`);
          } else if (geoFilter === 'all') {
            selectExtras.push(`geography`);
            groupBy.push('geography');
          } else {
            selectExtras.push(`'${geoFilter}' AS geography`);
          }

          // Add segment to output
          if (segFilter === 'total') {
            selectExtras.push(`'total' AS segment`);
          } else if (segFilter === 'all') {
            selectExtras.push(`segment`);
            groupBy.push('segment');
          } else {
            selectExtras.push(`'${segFilter}' AS segment`);
          }

          // Add scenario to output
          if (scenarioFilter === 'all') {
            selectExtras.push(`scenario_id`);
            groupBy.push('scenario_id');
          } else {
            selectExtras.push(`'${scenarioFilter}' AS scenario_id`);
          }

          sql = `
            SELECT
              CAST('${new Date(start).getFullYear()}-01-01' AS TIMESTAMP) + INTERVAL (CAST(year AS INTEGER) - ${new Date(start).getFullYear()}) YEAR AS period,
              ${selectExtras.join(', ')},
              SUM(total_value) AS value
            FROM read_parquet('${aggregatedTable}')
            WHERE ${wheres.join(' AND ')}
            GROUP BY ${groupBy.join(', ')}
            ORDER BY period
          `;
        }
      }

      if (!sql) {
        // Use new nested structure with both base and scenarios files
        const baseGlob = `${baseDir}/**/*.parquet`;
        const scenarioGlob = `${scenariosDir}/**/*.parquet`;

        // Build WHERE clauses for new schema
        const wheres = [
          `timestamp >= TIMESTAMP '${start}'`,
          `timestamp <= TIMESTAMP '${end}'`
        ];

        // geography filter
        if (geoFilter !== 'all' && geoFilter !== 'total') {
          wheres.push(`geography = '${geoFilter}'`);
        }

        // segment filter
        if (segFilter !== 'all' && segFilter !== 'total') {
          wheres.push(`segment = '${segFilter}'`);
        }

        // scenario filter
        if (scenarioFilter !== undefined && scenarioFilter !== 'all') {
          wheres.push(`scenario_id = '${scenarioFilter}'`);
        }

        // Build UNION query to combine base and scenarios directories
        let fromClause = '';
        const parts = [];

        if (fs.existsSync(baseDir)) {
          parts.push(`read_parquet('${baseGlob}')`);
        }

        if (fs.existsSync(scenariosDir)) {
          parts.push(`read_parquet('${scenarioGlob}')`);
        }

        if (parts.length > 1) {
          // Use UNION ALL to combine both directories with normalized schemas
          const baseQuery = `
            SELECT
              timestamp, value, geography, segment, scenario_id,
              NULL as housing_electrification,
              NULL as transport_electrification,
              NULL as industry_transition,
              true as is_base
            FROM read_parquet('${baseGlob}')
          `;
          const scenarioQuery = `
            SELECT
              timestamp, value, geography, segment, scenario_id,
              housing_electrification,
              transport_electrification,
              industry_transition,
              false as is_base
            FROM read_parquet('${scenarioGlob}')
          `;

          const unionParts = [];
          if (fs.existsSync(baseDir)) {
            unionParts.push(baseQuery);
          }
          if (fs.existsSync(scenariosDir)) {
            unionParts.push(scenarioQuery);
          }

          fromClause = `(${unionParts.join(' UNION ALL ')}) AS combined_data`;
        } else if (parts.length === 1) {
          fromClause = parts[0];
        } else {
          throw new Error('No data directories found');
        }

        sql = `
          SELECT
            ${timeExpr} AS "${timeAlias}",
            ${selectExtras.join(', ')},
            ${aggFunc}(combined_data.value) AS value
          FROM ${fromClause}
          WHERE ${wheres.join(' AND ')}
          GROUP BY ${groupBy.join(', ')}
          ORDER BY ${timeAlias}
        `;
      }

    console.log('SQL Query:', sql);
    console.log('Period start/end:', start, end);

    // 7) Execute
    const rawRows = await new Promise((ok, nok) =>
      conn.all(sql, (err, rows) => (err ? nok(err) : ok(rows)))
    );

    // 8) Clean BigInt
    const rows = rawRows.map(r =>
      Object.fromEntries(Object.entries(r).map(([k,v]) =>
        typeof v === 'bigint' ? [k, Number(v)] : [k,v]
      ))
    );

    // 9) Send back JSON or CSV
    if (fmt === 'csv') {
      const header = Object.keys(rows[0] || {}).join(',');
      const lines = rows.map(r => {
          return [
            // ensure ISO format for the period
            formatPeriod(r.period, resolution),
            r.geography,
            r.segment,
            r.scenario_id,
            r.value
          ].join(',');
      });
      res.type('text/csv').send([header, ...lines].join('\n'));
    } else {
      res.json(rows);
    }
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

// Fallbacks
api.register('notFound', (c, req, res) =>
  res.status(404).json({ error: 'Not found' })
);
api.register('validationFail', (c, req, res) =>
  res
    .status(400)
    .json({ error: 'Bad request', details: c.validation.errors })
);

const port = 4010;
app.listen(port, () => {
  console.log(`✅ Local server running at http://localhost:${port}`);
});
